### PR TITLE
Upgraded Elixir, all deps, and Dockerized

### PR DESCRIPTION
**Pull request by adriansalamon**
Changes:

* Now uses Elixir 1.17
* All deps upgraded to latest versions
* Switched to using [bandit](https://github.com/mtrudel/bandit) instead of `cowboy`
* Formatted all files using Elixir formatter
* Added Dockerfile that works
* Added docker-compose file to run
* Moved static files to `priv` folder for idiomatic Elixir 
* General small fixes and touchups

### CODE REVIEW

**Comment by foodelevator** [comment]
Made it possible to access login through different urls since when running locally the browser needs it to be `localhost` and the backend needs it to be the name of the service in the compose file. Seems work for me when running the compose file locally, but please do check that I didn't break anything :)

**Comment by adriansalamon** [comment]
I added a simpler dev Dockerfile, added a seed script, and made sure that everything runs well locally. Also did some cleanup, mostly in the `Auth` module.

**Comment by adriansalamon** [comment]
Vågar inte deploya det här, kan du testa/fixa? @foodelevator

**Comment by foodelevator** [comment]
Deployade från min dator och det verkar funka! (om man lägger till `65.109.233.61 pls.datasektionen.se` i /etc/hosts så ser man nya deployen)

**Review by foodelevator — APPROVED** [review]

**Pull request merged**
